Replace Pydantic with dataclasses
This gives us more control over the parsing and validating of a YAML mapping.

With Pydantic models it was impossible to tell which line in the input YAML triggered an error. With this refactor we have more control over the validation logic and can therefore display more meaningful error messages to the user.

For example, before:
```text
1 validation error for SignalMap
  Value error, Duplicate signal name in channel mapping: CWS-SCSU-CC2A-WCC-WPU1:CT1101-XI0. [type=value_error, input_value={'description': "Test map...2:PT2205-XI0 [kV]'})]})}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
```

After

```text
ValidationError: Duplicate signal name CWS-SCSU-CC2A-WCC-WPU1:CT1101-XI0
  in "../pon2imas/ci/test.mapping.yml", line 14:
        voltage/data: CWS-SCSU-CC2A-WCC-WPU1:CT1101-XI0 [kV]
```